language: c
sudo: required
env:
  global:
    - RACKET_DIR=~/racket
      HERBIE_SEED="0"
      UNIT="raco test ."
      HERBIE="racket $TRAVIS_BUILD_DIR/../herbie/infra/travis.rkt"
      INTEGRATION="$HERBIE --seed '${HERBIE_SEED}' herbie/bench/tutorial.rkt herbie/bench/hamming/"
      POSITS="$HERBIE bench/posits.fpcore"
  matrix:
    # separate builds for travis benches and unit tests
    - RACKET_VERSION="7.0" JOB="${POSITS}"
    - RACKET_VERSION="7.2" JOB="${POSITS}"
    - RACKET_VERSION="7.3" JOB="${POSITS}"
    - RACKET_VERSION="7.3" JOB="${UNIT}"
    - RACKET_VERSION="7.3" JOB="${INTEGRATION}"
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - git clone https://github.com/uwplse/herbie ../herbie/
  - raco pkg install --auto --name herbie $TRAVIS_BUILD_DIR/../herbie/src/
install:
  - raco pkg install --auto --name softposit-rkt $TRAVIS_BUILD_DIR
script:
  - echo ${JOB} && eval ${JOB}
notifications:
  slack:
    secure: QB8ib/gxZWZ8rY9H54BktIgx8LfjdqabSAkmWip0VHlUhrh2ULG566XgmB5h75eNzCil2cw76ma5wfSC0MNIQ1iDHKCxAgTE0+gcPcZAYGfucQ28sKGBG2wcuJfvBLG6lVDxj+luGUh3XohouTLYI9cg509JBgTgpcrXVexYAaE=
