name: Posit Benchmarks

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Install Packages"
        run: sudo apt-get install -y libmpfr6 libmpfr-dev
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v1.8
        with:
          version: stable
      - uses: actions/checkout@master
        with:
          path: plugin
      - name: "Check out Herbie"
        uses: actions/checkout@master
        with:
          repository: uwplse/herbie
          path: herbie
          ref: ${{ github.event.client_payload.branch }}
      - name: "Install Herbie"
        run: make install -C herbie/
      - name: "Install SoftPosit support"
        run: raco pkg install --no-cache --auto --name softposit-herbie plugin/
      - run: racket herbie/infra/ci.rkt --plugin "infra/plugins-ci.rkt" --platform softposit --precision posit16 --seed 0 plugin/bench/posits.fpcore
        env:
          RUST_BACKTRACE: full
